# Camera Caliibration

This notebook would give an overview on how to 

Perform Camera Calibration for a Generic Camera

In [1]:
import pathlib, os, pathlib

work_dir = os.path.abspath(os.getcwd())
work_dir_parent = pathlib.Path(work_dir).parent.absolute()

calib_pic_dir = os.path.join(work_dir_parent,'calibration_pics')

os.makedirs(calib_pic_dir, exist_ok=True)

In [2]:
import cv2
import numpy as np
from datetime import datetime

## Using USB Camera or PC Camera

Collect 15 or more images with the chessboard

Press "c" to capture image
Press "q to quit

In [6]:
frameWidth = 640
frameHeight = 480

cap = cv2.VideoCapture(0)
cap.set(3, frameWidth)
cap.set(4, frameHeight)
while True:
    success, img = cap.read()
    cv2.imshow("Live Capture", img)
    
    # process image here
    
    key  = cv2.waitKey(1)
    # press q to exit
    if key & 0xFF == ord('q'):
        break

    if key == ord("c"):
        now = datetime.now().strftime("%Y-%m-%d-%H%M%S")
        cv2.imwrite(calib_pic_dir+f'/{now}.jpg', img)

cv2.destroyAllWindows()
cap.release()

In [7]:
# set variables

dirpath = calib_pic_dir     # directory of the images
square_size = 0.025     # square size in meters
width = 9               # number of squares in width
height = 6              # number of squares in height
visualize = True        # visualize process



# perform calibration
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(8,6,0)
objp = np.zeros((height*width, 3), np.float32)
objp[:, :2] = np.mgrid[0:width, 0:height].T.reshape(-1, 2)
objp = objp * square_size
# Arrays to store object points and image points from all the images.
objpoints = []  # 3d point in real world space
imgpoints = []  # 2d points in image plane.
images = os.listdir(dirpath)
for fname in images:
    img = cv2.imread(os.path.join(dirpath, fname))
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    # Find the chess board corners
    ret, corners = cv2.findChessboardCorners(gray, (width, height), None)
    # If found, add object points, image points (after refining them)
    if ret:
        objpoints.append(objp)
        corners2 = cv2.cornerSubPix(gray, corners, (11, 11), (-1, -1), criteria)
        imgpoints.append(corners2)
        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, (width, height), corners2, ret)
    if visualize:
        cv2.imshow('img',img)
        cv2.waitKey(0)

cv2.destroyAllWindows()

ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

In [11]:
np.save("calibration_matrix", mtx)
np.save("distortion_coefficients", dist)

In [ ]:
mtx = np.load("path to saved parameter")

In [12]:
# check the contents of the camera calibration matrix
mtx

array([[564.15086642,   0.        , 310.17079762],
       [  0.        , 564.38233768, 218.32729484],
       [  0.        ,   0.        ,   1.        ]])

In [13]:
# check the distortion coefficients
dist

array([[ 0.14656932, -0.6135718 , -0.01280436, -0.00647902,  0.89636832]])

In [14]:
# undistorting image method 1

img_test = cv2.imread("/home/richard/realsense_workshop/day_2_am/calibration_pics/2024-08-25-220749.jpg")

h,  w = img_test.shape[:2]
newcameramtx, roi = cv2.getOptimalNewCameraMatrix(mtx, dist, (w,h), 1, (w,h))

# undistort
dst = cv2.undistort(img_test, mtx, dist, None, newcameramtx)
 
# crop the image
x, y, w, h = roi
dst = dst[y:y+h, x:x+w]


cv2.imshow("Distorted", img_test)
cv2.imshow("Undistorted", dst)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# undistorting image, method2

mapx, mapy = cv2.initUndistortRectifyMap(mtx, dist, None, newcameramtx, (w,h), 5)
dst = cv2.remap(img_test, mapx, mapy, cv2.INTER_LINEAR)
 
# crop the image
x, y, w, h = roi
dst = dst[y:y+h, x:x+w]


cv2.imshow("Distorted", img_test)
cv2.imshow("Undistorted", dst)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
# example, a point is located at coordinates (2,2,2) with respect to the camera frame, what would be its location in terms of pixels

point_A = np.array([2,2,2]).transpose()
point_A

array([2, 2, 2])

In [20]:
mtx

array([[564.15086642,   0.        , 310.17079762],
       [  0.        , 564.38233768, 218.32729484],
       [  0.        ,   0.        ,   1.        ]])

In [21]:
pixelA = np.matmul(mtx,point_A)

In [23]:
pixelA/2

array([874.32166404, 782.70963252,   1.        ])

In [ ]:
np.round(pixelA).astype(int)

In [26]:
pixelB = np.array([600,400,1]).transpose()

In [27]:
point_B = np.matmul(np.linalg.inv(mtx), pixelB)

In [28]:
point_B

array([0.51374414, 0.32189651, 1.        ])

In [29]:
!rs-enumerate-devices -c

Device info: 
    Name                          : 	Intel RealSense D435
    Serial Number                 : 	829212072157
    Firmware Version              : 	5.16.0.1
    Recommended Firmware Version  : 	5.16.0.1
    Physical Port                 : 	/sys/devices/pci0000:00/0000:00:08.1/0000:65:00.3/usb2/2-1/2-1:1.0/video4linux/video4
    Debug Op Code                 : 	15
    Advanced Mode                 : 	YES
    Product Id                    : 	0B07
    Camera Locked                 : 	YES
    Usb Type Descriptor           : 	3.2
    Product Line                  : 	D400
    Asic Serial Number            : 	830213021120
    Firmware Update Id            : 	830213021120
    Dfu Device Path               : 	

Stream Profiles supported by Stereo Module
 Supported modes:
    STREAM      RESOLUTION     FORMAT      FPS
    Infrared 1  1280x800       Y16         @ 25/15 Hz
    Infrared 1      |          Y8          @ 30/15 Hz
    Infrared 1  1280x720       Y8          @ 30/15/6 Hz
    I